<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>

  <parent>
    <groupId>com.itextpdf</groupId>
    <artifactId>pdfocr-root</artifactId>
    <version>5.0.1</version>
  </parent>

  <artifactId>pdfocr-onnx-cpu</artifactId>

  <name>pdfOCR-Onnx-CPU</name>
  <description>pdfOCR-Onnx-CPU is an iText add-on for Java to recognize and extract text in scanned documents and images. It can also convert them into fully ISO-compliant PDF or PDF/A-3u files that are accessible, searchable, and suitable for archiving</description>
  <dependencies>
    <dependency>
      <groupId>com.itextpdf</groupId>
      <artifactId>pdfocr-onnx-abstract</artifactId>
      <version>${project.version}</version>
    </dependency>
    <dependency>
      <groupId>com.microsoft.onnxruntime</groupId>
      <artifactId>onnxruntime</artifactId>
      <version>${onnxruntime.version}</version>
    </dependency>
    <dependency>
      <groupId>com.itextpdf</groupId>
      <artifactId>pdftest</artifactId>
      <version>${itext.version}</version>
      <scope>test</scope>
    </dependency>
  </dependencies>

  <properties>
    <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    <sharpen.phase>install</sharpen.phase>
    <sharpen.projectName>pdfocr-onnx-cpu</sharpen.projectName>
    <sharpen.cSharpTargetFolder>./../../../sharp/pdfocr</sharpen.cSharpTargetFolder>
    <sharpen.cSharpSourceCodeDestination>itext/itext.pdfocr.onnx.cpu</sharpen.cSharpSourceCodeDestination>
    <sharpen.cSharpTestCodeDestination>itext.tests/itext.pdfocr.onnx.cpu.tests</sharpen.cSharpTestCodeDestination>
  </properties>

</project>